import '../../../style/scss/style.scss';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { Header } from '../../../components/Header/Header';

export const metadata: Metadata = {
    title: 'Главная | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='body'>
                <Header />
                <main className='main'>{children}</main>
            </body>
        </html>
    );
}
