import '../../style/scss/style.scss';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { Header } from '../../components/Header/Header';

const nunito = Nunito({
    variable: '--font-Nunito',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='body'>
                <Header />
                {children}
            </body>
        </html>
    );
}
