import { Providers } from '../../Shared/Providers/Providers';
import '../../style/scss/style.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Главная | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='body'>
                <main className='main'>
                    <Providers>{children}</Providers>
                </main>
            </body>
        </html>
    );
}
