import '../../../style/scss/style.scss';
import type { Metadata } from 'next';

import { Header } from '../../../components/Header/Header';

export const metadata: Metadata = {
    title: 'Главная | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function ProductIdLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className='body'>
                <Header />
                {children}
            </div>
        </>
    );
}
