import '../../../style/scss/style.scss';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { Header } from '../../../components/Header/Header';

const nunito = Nunito({
    variable: '--font-Nunito',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Главная | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function OrderLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='body'>{children}</body>
        </html>
    );
}
